name: npm publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install Depencencies
        run: yarn install

      - name: Build, Test, and Package
        run: yarn preversion

      - name: Publish npm package
        run: |
          npm deprecate soroban-client@"<1.0.0" "👋 This package will no longer receive updates. Please migrate to stellar-sdk@^11.0.0, instead!"
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
